'use server';

import { revalidatePath } from 'next/cache';
import { redirect } from 'next/navigation';
import { createClient } from '@/lib/supabase/server';
import { requireAdmin } from '@/lib/auth';
import { logAudit } from '@/lib/audit';
import type { CommandType, Priority, ExecTarget, ExecMode } from '@/lib/command-centre/cc';

const s = (fd: FormData, k: string) => (fd.get(k)?.toString().trim() || null);

// Owner sends a command to an agent. Saved as QUEUED in Supabase for the (future)
// Mac Studio runner to claim. Nothing executes here.
export async function createCommand(formData: FormData): Promise<{ error?: string; id?: string }> {
  const profile = await requireAdmin();
  const supabase = createClient();

  const prompt = s(formData, 'prompt');
  if (!prompt) return { error: 'Enter a command / instruction.' };
  const agentId = s(formData, 'agent_id');

  const { data, error } = await supabase
    .from('agent_commands')
    .insert({
      agent_id: agentId,
      created_by: profile.id,
      title: s(formData, 'title') ?? prompt.slice(0, 80),
      prompt,
      command_type: (s(formData, 'command_type') as CommandType) ?? 'analyse',
      priority: (s(formData, 'priority') as Priority) ?? 'medium',
      status: 'queued',
      execution_target: (s(formData, 'execution_target') as ExecTarget) ?? 'mac_studio',
      execution_mode: (s(formData, 'execution_mode') as ExecMode) ?? 'local_agent',
    })
    .select('id')
    .single();
  if (error || !data) return { error: `Could not queue command: ${error?.message}` };

  await supabase.from('agent_command_messages').insert({ command_id: data.id, sender_type: 'owner', message: prompt });
  await logAudit({ actorId: profile.id, action: 'command.create', entityType: 'agent_command', entityId: data.id, metadata: { agentId } });

  revalidatePath('/command-centre');
  revalidatePath('/command-centre/commands');
  revalidatePath('/command-centre/terminal');
  return { id: data.id };
}

// Convenience wrapper for <form action>: queue then redirect to the command detail.
export async function createCommandAndOpen(formData: FormData) {
  const res = await createCommand(formData);
  if (res.id) redirect(`/command-centre/commands/${res.id}`);
}

// ADMIN/DEV-ONLY demo helper: simulate the runner completing a command so the UI
// can be tested end-to-end. Does NOT execute anything locally.
export async function markDemoCompleted(commandId: string): Promise<{ error?: string }> {
  const profile = await requireAdmin();
  const supabase = createClient();

  const { error } = await supabase
    .from('agent_commands')
    .update({
      status: 'completed',
      result_summary: 'DEMO: command marked completed from the portal to test the UI. No local execution occurred.',
      started_at: new Date(Date.now() - 60_000).toISOString(),
      completed_at: new Date().toISOString(),
    })
    .eq('id', commandId);
  if (error) return { error: error.message };

  await supabase.from('agent_command_results').insert({
    command_id: commandId, result_type: 'summary', title: 'Demo result',
    content: 'This is a demo result generated by the "Mark demo completed" action. The real Mac Studio Agent Runner will replace this with live output.',
  });
  await supabase.from('agent_command_messages').insert({ command_id: commandId, sender_type: 'system', message: 'Command marked completed (demo).' });
  await supabase.from('agent_run_logs').insert({ command_id: commandId, log_level: 'info', message: 'Demo completion triggered from portal.' });
  await logAudit({ actorId: profile.id, action: 'command.demo_complete', entityType: 'agent_command', entityId: commandId });

  revalidatePath(`/command-centre/commands/${commandId}`);
  revalidatePath('/command-centre/commands');
  return {};
}

// Owner decision on an approval.
export async function decideApproval(
  id: string, decision: 'approved' | 'rejected' | 'snoozed', note?: string,
): Promise<{ error?: string }> {
  const profile = await requireAdmin();
  const supabase = createClient();
  const { error } = await supabase
    .from('owner_approvals')
    .update({ status: decision, decided_by: profile.id, decided_at: new Date().toISOString(), decision_note: note ?? null })
    .eq('id', id);
  if (error) return { error: error.message };
  await logAudit({ actorId: profile.id, action: `approval.${decision}`, entityType: 'owner_approval', entityId: id });
  revalidatePath('/command-centre/approvals');
  revalidatePath('/command-centre');
  return {};
}

// Create a business task (owner or on behalf of an agent).
export async function createTask(formData: FormData): Promise<{ error?: string }> {
  await requireAdmin();
  const supabase = createClient();
  const title = s(formData, 'title');
  if (!title) return { error: 'Task title required.' };
  const { error } = await supabase.from('business_tasks').insert({
    title,
    description: s(formData, 'description'),
    source_module: (s(formData, 'source_module') as any) ?? 'command_centre',
    agent_id: s(formData, 'agent_id'),
    priority: (s(formData, 'priority') as any) ?? 'medium',
    status: 'todo',
    due_at: s(formData, 'due_at') ? new Date(s(formData, 'due_at')!).toISOString() : null,
  });
  if (error) return { error: error.message };
  revalidatePath('/command-centre/tasks');
  revalidatePath('/command-centre');
  return {};
}

// Move a task through the board.
export async function setTaskStatus(id: string, status: 'todo' | 'in_progress' | 'blocked' | 'done' | 'cancelled'): Promise<{ error?: string }> {
  await requireAdmin();
  const supabase = createClient();
  const { error } = await supabase.from('business_tasks').update({ status }).eq('id', id);
  if (error) return { error: error.message };
  revalidatePath('/command-centre/tasks');
  revalidatePath('/command-centre');
  return {};
}

// Owner idea -> agent-orchestrated business plan. The idea is queued as a
// Chief-of-Staff command; the Mac Studio generates a grounded plan assigning
// every agent its role, files it back, and seeds the tasks. Nothing executes
// beyond planning without the owner's approval.
export async function createIdeaPlan(formData: FormData): Promise<{ error?: string; id?: string }> {
  const profile = await requireAdmin();
  const supabase = createClient();
  const idea = s(formData, 'idea');
  if (!idea) return { error: 'Type an idea first.' };

  const prompt = `OWNER IDEA (from Yasmin, via the Command Centre idea box): "${idea}"

You are the CHIEF OF STAFF for Beyond Reason Pty Ltd (Milk & Honey Wigs PREMIUM + MH Wigs Outlet —
two separate businesses, never blended). Turn this idea into a decision-grade BUSINESS PLAN that
orchestrates the agent team. Ground every claim in real data: read ~/business-brain (CLAUDE.md,
knowledge/, the GROWTH-LEDGER, each arm's GAME-PLAN and latest daily reports) and pull live figures
from the portal DB via Supabase REST (creds in ~/mhw-production-portal/.env.local). NEVER invent a
number — cite the source or write [DATA NEEDED].

THE PLAN (keep it tight, owner-readable):
1. THE PLAY — what we're doing and why now, in 3 sentences, with the key numbers.
2. PHASES — 2-4 phases with entry/exit criteria.
3. AGENT ASSIGNMENTS — for EACH relevant agent (Mabel/production, Claudia/customer service,
   SEO agent, Marketing agent, and the planned Inventory/Finance/Partnerships agents where relevant):
   their specific role, their first 3 concrete tasks, and what they report back.
4. NEEDS OWNER — approvals, budgets, logins or decisions required, one line each.
5. RISKS — top 3 with mitigations.
6. FIRST 7 DAYS — day-by-day what happens if approved today.
7. SUCCESS METRICS — what we re-measure and when.

THEN MAKE IT REAL: insert one business_tasks row per agent assignment (Supabase REST:
title = the agent's first task, description = their role in this plan + "From owner idea: ${idea}",
source_module = the agent's module, agent_id = the agent's id from the agents table, status = 'todo',
priority = 'high'). These appear on each agent's Workboard and the Tasks board.

Report per the AGENT-REPORTING-STANDARD; the full plan IS the report. Sign as "Chief of Staff".`;

  const { data, error } = await supabase.from('agent_commands').insert({
    agent_id: null,
    created_by: profile.id,
    title: `Business plan: ${idea.slice(0, 70)}`,
    prompt,
    command_type: 'workflow',
    priority: 'high',
    status: 'queued',
    execution_target: 'mac_studio',
    execution_mode: 'local_agent',
  }).select('id').single();
  if (error || !data) return { error: `Could not queue the plan: ${error?.message}` };
  await logAudit({ actorId: profile.id, action: 'idea.plan', entityType: 'agent_command', entityId: data.id, metadata: { idea } });
  revalidatePath('/command-centre');
  return { id: data.id };
}

// Generic module-item approval: approve/reject any agent's drafted item by table.
// WHITELISTED tables + their status column only — nothing else reachable.
const APPROVABLE: Record<string, { column: string; approve: string; reject: string }> = {
  seo_product_page_opportunities: { column: 'status', approve: 'approved', reject: 'dismissed' },
  seo_collection_opportunities: { column: 'approval_status', approve: 'approved', reject: 'dismissed' },
  seo_schema_opportunities: { column: 'approval_status', approve: 'approved', reject: 'dismissed' },
  seo_geo_opportunities: { column: 'approval_status', approve: 'approved', reject: 'dismissed' },
  seo_optimisation_opportunities: { column: 'status', approve: 'approved', reject: 'dismissed' },
  seo_content_plan: { column: 'status', approve: 'approved', reject: 'dismissed' },
  claudia_optimisation_opportunities: { column: 'status', approve: 'approved', reject: 'dismissed' },
  mkt_cro_opportunities: { column: 'approval_status', approve: 'approved', reject: 'dismissed' },
  mkt_creative_requests: { column: 'status', approve: 'approved', reject: 'dismissed' },
  mkt_email_opportunities: { column: 'status', approve: 'approved', reject: 'dismissed' },
  mkt_campaign_calendar: { column: 'status', approve: 'approved', reject: 'cancelled' },
  mkt_growth_experiments: { column: 'status', approve: 'approved', reject: 'dismissed' },
  mkt_budget_recommendations: { column: 'status', approve: 'approved', reject: 'dismissed' },
};

export async function decideModuleItem(
  table: string, id: string, decision: 'approve' | 'reject', note?: string,
): Promise<{ error?: string }> {
  const profile = await requireAdmin();
  const spec = APPROVABLE[table];
  if (!spec) return { error: `Not an approvable table: ${table}` };
  const supabase = createClient();
  const update: Record<string, unknown> = { [spec.column]: decision === 'approve' ? spec.approve : spec.reject };
  // Owner note travels with the item — the agent reads it when implementing.
  if (note?.trim()) update.decision_note = `${decision === 'approve' ? 'APPROVED' : 'DENIED'} by owner ${new Date().toISOString().slice(0, 10)}: ${note.trim()}`.slice(0, 1000);
  const { error } = await supabase.from(table).update(update).eq('id', id);
  if (error) return { error: error.message };
  await logAudit({ actorId: profile.id, action: `module_item.${decision}`, entityType: table, entityId: id, metadata: note ? { note } : undefined });

  // IMMEDIATE EXECUTION: approving queues an implement-command for the owning
  // agent; the Mac Studio runner picks it up within ~15s (no waiting for the
  // daily run). One open implement-command per agent — approvals batch into it.
  if (decision === 'approve') {
    const slug = table.startsWith('claudia_') ? 'claudia-customer-service'
      : table.startsWith('mkt_') ? 'marketing-agent' : 'seo-agent';
    const { data: agent } = await supabase.from('agents').select('id').eq('slug', slug).maybeSingle();
    if (agent) {
      const { data: openCmd } = await supabase
        .from('agent_commands').select('id')
        .eq('agent_id', agent.id).in('status', ['queued', 'claimed'])
        .ilike('title', 'Implement owner-approved%').limit(1).maybeSingle();
      if (!openCmd) {
        await supabase.from('agent_commands').insert({
          agent_id: agent.id,
          created_by: profile.id,
          title: 'Implement owner-approved items (auto-queued on approval)',
          prompt: slug === 'marketing-agent'
            ? 'The owner has just APPROVED one or more Marketing items in the Command Centre. Read the Supabase creds from ~/mhw-production-portal/.env.local (Bash) and query via REST the tables mkt_cro_opportunities, mkt_creative_requests, mkt_email_opportunities, mkt_campaign_calendar, mkt_growth_experiments, mkt_budget_recommendations for every row with status/approval_status = \'approved\'. Implement each per your OPERATING-SYSTEM rules: produce the finished work product (test design, staged campaign build, flow draft, creative brief, reallocation plan) in arms/marketing/ — you still NEVER spend money, launch/pause ads, send email or change the live store; approval authorises the WORK, execution of spend stays with the owner. Read decision_note for owner instructions. PATCH implemented rows to \'implemented\' (or \'in_production\'/\'approved\'-appropriate next status for creative/calendar). Report per the AGENT-REPORTING-STANDARD: RESULTS / DONE / NEXT / BLOCKED / NEEDS YOU.'
            : slug === 'seo-agent'
            ? 'The owner has just APPROVED one or more SEO items in the Command Centre. Read the Supabase creds from ~/mhw-production-portal/.env.local (Bash) and query via REST the tables seo_product_page_opportunities, seo_collection_opportunities, seo_schema_opportunities, seo_optimisation_opportunities, seo_geo_opportunities, seo_content_plan for every row with status/approval_status = \'approved\'. Implement EACH per your standing autonomy + execution rules (publish via scoped Shopify token if present, otherwise produce finished publish-ready output in the seo-geo working files; NEVER touch product titles/descriptions; visual copy was approved by the owner so it may be finalised). Read each row\'s decision_note for owner instructions. After implementing an item, PATCH its status/approval_status to \'implemented\'. Finish with a concise report of exactly what was done per item and anything blocked (e.g. missing Shopify token) and why.'
            : 'The owner has just APPROVED one or more Claudia optimisation items in the Command Centre. Read the Supabase creds from ~/mhw-production-portal/.env.local (Bash) and query via REST claudia_optimisation_opportunities for rows with status = \'approved\'. Implement each per Claudia\'s rules (templates/knowledge/rules work inside her repo and the business brain; drafts only, nothing customer-facing is sent). Read decision_note for owner instructions. PATCH implemented rows to status \'completed\'. Report exactly what was done per item.',
          command_type: 'workflow',
          priority: 'high',
          status: 'queued',
          execution_target: 'mac_studio',
          execution_mode: 'local_agent',
        });
      }
    }
  }

  revalidatePath('/command-centre/agents/seo-agent');
  revalidatePath('/command-centre/agents/claudia-customer-service');
  revalidatePath('/command-centre');
  return {};
}

// Claudia module: move an optimisation opportunity through its lifecycle.
export async function setOpportunityStatus(
  id: string, status: 'suggested' | 'approved' | 'in_progress' | 'completed' | 'dismissed',
): Promise<{ error?: string }> {
  await requireAdmin();
  const supabase = createClient();
  const { error } = await supabase.from('claudia_optimisation_opportunities').update({ status }).eq('id', id);
  if (error) return { error: error.message };
  revalidatePath('/command-centre/agents/claudia-customer-service');
  return {};
}

// Owner action on a risk.
export async function updateRiskStatus(
  id: string, status: 'acknowledged' | 'resolved' | 'dismissed',
): Promise<{ error?: string }> {
  const profile = await requireAdmin();
  const supabase = createClient();
  const { error } = await supabase
    .from('owner_risks')
    .update({ status, resolved_at: status === 'resolved' ? new Date().toISOString() : null })
    .eq('id', id);
  if (error) return { error: error.message };
  await logAudit({ actorId: profile.id, action: `risk.${status}`, entityType: 'owner_risk', entityId: id });
  revalidatePath('/command-centre/risks');
  revalidatePath('/command-centre');
  return {};
}
