'use server';

import { revalidatePath } from 'next/cache';
import { redirect } from 'next/navigation';
import { createClient } from '@/lib/supabase/server';
import { requireAdmin } from '@/lib/auth';
import { logAudit } from '@/lib/audit';
import type { CommandType, Priority, ExecTarget, ExecMode } from '@/lib/command-centre/cc';

const s = (fd: FormData, k: string) => (fd.get(k)?.toString().trim() || null);

// Owner sends a command to an agent. Saved as QUEUED in Supabase for the (future)
// Mac Studio runner to claim. Nothing executes here.
export async function createCommand(formData: FormData): Promise<{ error?: string; id?: string }> {
  const profile = await requireAdmin();
  const supabase = createClient();

  const prompt = s(formData, 'prompt');
  if (!prompt) return { error: 'Enter a command / instruction.' };
  const agentId = s(formData, 'agent_id');

  const { data, error } = await supabase
    .from('agent_commands')
    .insert({
      agent_id: agentId,
      created_by: profile.id,
      title: s(formData, 'title') ?? prompt.slice(0, 80),
      prompt,
      command_type: (s(formData, 'command_type') as CommandType) ?? 'analyse',
      priority: (s(formData, 'priority') as Priority) ?? 'medium',
      status: 'queued',
      execution_target: (s(formData, 'execution_target') as ExecTarget) ?? 'mac_studio',
      execution_mode: (s(formData, 'execution_mode') as ExecMode) ?? 'local_agent',
    })
    .select('id')
    .single();
  if (error || !data) return { error: `Could not queue command: ${error?.message}` };

  await supabase.from('agent_command_messages').insert({ command_id: data.id, sender_type: 'owner', message: prompt });
  await logAudit({ actorId: profile.id, action: 'command.create', entityType: 'agent_command', entityId: data.id, metadata: { agentId } });

  revalidatePath('/command-centre');
  revalidatePath('/command-centre/commands');
  revalidatePath('/command-centre/terminal');
  return { id: data.id };
}

// Convenience wrapper for <form action>: queue then redirect to the command detail.
export async function createCommandAndOpen(formData: FormData) {
  const res = await createCommand(formData);
  if (res.id) redirect(`/command-centre/commands/${res.id}`);
}

// ADMIN/DEV-ONLY demo helper: simulate the runner completing a command so the UI
// can be tested end-to-end. Does NOT execute anything locally.
export async function markDemoCompleted(commandId: string): Promise<{ error?: string }> {
  const profile = await requireAdmin();
  const supabase = createClient();

  const { error } = await supabase
    .from('agent_commands')
    .update({
      status: 'completed',
      result_summary: 'DEMO: command marked completed from the portal to test the UI. No local execution occurred.',
      started_at: new Date(Date.now() - 60_000).toISOString(),
      completed_at: new Date().toISOString(),
    })
    .eq('id', commandId);
  if (error) return { error: error.message };

  await supabase.from('agent_command_results').insert({
    command_id: commandId, result_type: 'summary', title: 'Demo result',
    content: 'This is a demo result generated by the "Mark demo completed" action. The real Mac Studio Agent Runner will replace this with live output.',
  });
  await supabase.from('agent_command_messages').insert({ command_id: commandId, sender_type: 'system', message: 'Command marked completed (demo).' });
  await supabase.from('agent_run_logs').insert({ command_id: commandId, log_level: 'info', message: 'Demo completion triggered from portal.' });
  await logAudit({ actorId: profile.id, action: 'command.demo_complete', entityType: 'agent_command', entityId: commandId });

  revalidatePath(`/command-centre/commands/${commandId}`);
  revalidatePath('/command-centre/commands');
  return {};
}

// Owner decision on an approval.
export async function decideApproval(
  id: string, decision: 'approved' | 'rejected' | 'snoozed', note?: string,
): Promise<{ error?: string }> {
  const profile = await requireAdmin();
  const supabase = createClient();
  const { error } = await supabase
    .from('owner_approvals')
    .update({ status: decision, decided_by: profile.id, decided_at: new Date().toISOString(), decision_note: note ?? null })
    .eq('id', id);
  if (error) return { error: error.message };
  await logAudit({ actorId: profile.id, action: `approval.${decision}`, entityType: 'owner_approval', entityId: id });
  revalidatePath('/command-centre/approvals');
  revalidatePath('/command-centre');
  return {};
}

// Owner action on a risk.
export async function updateRiskStatus(
  id: string, status: 'acknowledged' | 'resolved' | 'dismissed',
): Promise<{ error?: string }> {
  const profile = await requireAdmin();
  const supabase = createClient();
  const { error } = await supabase
    .from('owner_risks')
    .update({ status, resolved_at: status === 'resolved' ? new Date().toISOString() : null })
    .eq('id', id);
  if (error) return { error: error.message };
  await logAudit({ actorId: profile.id, action: `risk.${status}`, entityType: 'owner_risk', entityId: id });
  revalidatePath('/command-centre/risks');
  revalidatePath('/command-centre');
  return {};
}
