'use server';

import { createClient } from '@/lib/supabase/server';
import { requireStaff } from '@/lib/auth';
import { logAudit } from '@/lib/audit';
import { generateSupplierInstruction } from '@/lib/business/supplier-instruction';
import type { Order, Customer } from '@/lib/types';

// Generate the supplier-facing instruction text for an order and LOG it.
// v1 does not email — the UI shows the text to copy.
export async function generateSupplierInstructionText(orderId: string): Promise<{ text?: string; error?: string }> {
  const profile = await requireStaff();
  const supabase = createClient();

  const { data: order } = await supabase.from('orders').select('*').eq('id', orderId).single();
  if (!order) return { error: 'Order not found.' };
  const { data: customer } = order.customer_id
    ? await supabase.from('customers').select('*').eq('id', order.customer_id).single()
    : { data: null };

  const text = generateSupplierInstruction(order as Order, customer as Customer | null);

  await logAudit({ actorId: profile.id, action: 'order.generate_instruction', entityType: 'order', entityId: orderId });
  await supabase.from('supplier_updates').insert({
    order_id: orderId, supplier_id: order.supplier_id, update_type: 'general_note',
    message: 'Supplier instruction generated by staff.', created_by: profile.id,
  });
  return { text };
}
